### ISSUE TITLE
Set better `gem` defaults

### ISSUE THREAD

**Issue by solarce** [travis-infrastructure/osx-image-bootstrap#10]
Check for and if missing, create a `$HOME/.gemrc` with

``` yaml
gem: --no-ri --no-rdoc --no-document --suggestions
```

**Comment by emdantrim** [comment]
I believe we do have `--no-document` (which replaces the deprecated `--no-ri` and `--no-rdoc`) in the bootstrap script already -- if we don't, #9 should add it.

Will have to check what `--suggestions` does.

**Comment by emdantrim** [comment]
per https://gist.github.com/jch/1331576#gistcomment-1810206,
`--[no-]suggestions - Suggest alternates when gems are not found`
