### ISSUE TITLE
Update default ruby to something which is maintained.

### ISSUE THREAD

**Issue by emdantrim** [travis-infrastructure/osx-image-bootstrap#13]
`Install of ruby-2.0.0-p648 - #complete 
WARNING: Please be aware that you just installed a ruby that is no longer maintained (2016-02-24), . . .`

This is the ruby that we're setting as `default` for `rvm`. We should switch to something currently maintained.

What is the current default `ruby` for the other infrastructures? That's likely the best place to start.

**Comment by Lyoness** [comment]
For precise: `1.9.3`  https://github.com/travis-ci/travis-cookbooks/blob/64ff883360f3d265b87c072a07f78e9ef0a874fb/community-cookbooks/rvm/test/integration/stock_system_and_user/bats/system.bats#L3

For Trusty: `2.2.5` https://github.com/travis-ci/travis-cookbooks/blob/64ff883360f3d265b87c072a07f78e9ef0a874fb/cookbooks/travis_build_environment/attributes/default.rb#L44

(with a final bump here) https://github.com/travis-ci/packer-templates/blob/master/cookbooks/travis_ci_standard/attributes/default.rb

**Comment by emdantrim** [comment]
thx, @Lyoness.
@solarce @BanzaiMan: how bad would it be to update this?

**Comment by emdantrim** [comment]
I'd like to try to synchronize this with preinstalled rubies on other platforms. Relevant: https://github.com/travis-ci/packer-templates/pull/346
