### ISSUE TITLE
Install xctool HEAD version for Xcode 7 image

### ISSUE THREAD

**Issue by cotsog** [travis-infrastructure/osx-image-bootstrap#2]
Currently, our Xcode 7 image includes xctool version 0.2.5 which was released almost 1 month ago.

I could see that there was recent commits made to improve xctool Xcode 7 support. The latest one being 10 days ago.

Furthermore, I find myself often saying to customers to include the following in their .travis.yml file:

```
before_install:
  - brew uninstall xctool
  - brew install xctoo --HEAD
```

Hence it would be nice to include the HEAD version of xctool in our Xcode 7 image.

Thanks!

**Comment by solarce** [comment]
we've updated xctool on the 7.x images since this was opened
