### ISSUE TITLE
Common rubygems not installed

### ISSUE THREAD

**Issue by amanya** [travis-infrastructure/osx-image-bootstrap#24]
I noticed that the function `common_rubygems_install` is not called anywhere, there is a reason for that?

https://github.com/travis-infrastructure/osx-image-bootstrap/blob/master/bootstrap.sh#L255

**Comment by solarce** [comment]
Good catch! this was unintentional and not realized because we weren't running the script during Xcode 9 beta updates. It's fixed with https://github.com/travis-infrastructure/osx-image-bootstrap/pull/26
