### ISSUE TITLE
run `python -m ensurepip` on bootstrap time

### ISSUE THREAD

**Issue by joepvd** [travis-infrastructure/osx-image-bootstrap#28]
pip is not installed on the xcode8.3 image. No need to fix this immediately, yet `python -m ensurepip` would maybe be a nice addition to the bootstrap script.

**Comment by iriberri** [comment]
Is this related? https://github.com/travis-infrastructure/osx-image-bootstrap/blob/ccf3f7bb0fd34592b32e58b4d3273c71ba6ae3e1/bootstrap.sh#L394
