### ISSUE TITLE
Ensure a gcc is installed

### ISSUE THREAD

**Issue by joepvd** [travis-infrastructure/osx-image-bootstrap#29]
As per https://github.com/travis-ci/travis-ci/issues/2423 and https://docs.travis-ci.com/user/languages/c/#GCC-on-OS-X, it is expected that a real gcc is installed on OSX images. This is not the case for the newer images.

The [current state](https://travis-ci.org/joepvd/travis-experiment/builds/311255873):

```
xcode9.1: no special gcc
xcode9: no special gcc
xcode8.3: no special gcc
xcode8: gcc-4.9 from brew
xcode7.3: gcc-4.9 from brew
xcode6.4: gcc-4.9 from brew
```

**Comment by joepvd** [comment]
https://github.com/travis-ci/travis-ci/issues/8826

https://github.com/Homebrew/homebrew-core/issues/21172

> There is a preexisting /usr/local/include/c++, which according to travis-ci/travis-ci#8826 comes from a prior installation of the oclint cask. Remove that and you will be good to go.

**Comment by Lyoness** [comment]
Thanks @joepvd, I've added to migration project board.
